# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "113010875edcf85ffa337195c5b2275a"
name = "minimalreviews"
handle = "minimalreviews"
application_url = "https://minimalreviews.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "lojatesteigor.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/fulfilled" ]
  uri = "/webhooks/orders/fulfilled"

  [[webhooks.subscriptions]]
  topics = [ "orders/paid" ]
  uri = "/webhooks/orders/paid"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://minimalreviews.vercel.app/auth/callback", 
  "https://minimalreviews.vercel.app/auth/shopify/callback", 
  "https://minimalreviews.vercel.app/api/auth/callback"
]

[app_proxy]
url = "https://cheaper-effectiveness-schemes-hopefully.trycloudflare.com/apps/minimalreviews"
subpath = "minimalreviews"
prefix = "apps"

[pos]
embedded = false
